<a href="https://colab.research.google.com/github/rokon156/Krish_Naik_38_ML/blob/main/kr_logisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

binary classifier korbo tai setosa hotaye dibo

In [ ]:
df = df[df['species']!='setosa']

In [ ]:
df['species']=df['species'].map({'versicolor':0, 'virginica':1})

In [ ]:
df.head()

    sepal_length  sepal_width  petal_length  petal_width  species
50           7.0          3.2           4.7          1.4        0
51           6.4          3.2           4.5          1.5        0
52           6.9          3.1           4.9          1.5        0
53           5.5          2.3           4.0          1.3        0
54           6.5          2.8           4.6          1.5        0

split datasets into dependent and indepedent features

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=43)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = {'penalty':['l1','l2','elasticnet'], 'C':[1,2,3,4,5,6,8,10,20,30,40,50,60], 'max_iter':[100,200,300]}

In [ ]:
classifier_regressior = GridSearchCV(lr,param_grid=parameters, scoring='accuracy', cv=5)

In [ ]:
classifier_regressior.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
390 fits failed out of a total of 585.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
195 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
195 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.96              nan        nan 0.96              nan
        nan 0.96              nan        nan 0.96              nan
        nan 0.96              nan        nan 0.96              nan
        nan 0.96              nan        nan 0.96              nan
        nan 0.96              nan        nan 0.96              nan
        nan 0.96              nan        nan 0.96              nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.97333333        nan
        nan 0.97333333        nan        nan 0.96              nan
        nan 0.96              nan        nan 0.96              nan
        nan 0.96              nan        nan 0.96              nan
        nan 0.96              nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 8, 10, 20, 30, 40, 50, 60],
                         'max_iter': [100, 200, 300],
                         'penalty': ['l1', 'l2', 'elasticnet']},
             scoring='accuracy')

In [ ]:
print(classifier_regressior.best_params_)

{'C': 5, 'max_iter': 100, 'penalty': 'l2'}

In [ ]:
classifier_regressior.best_score_

np.float64(0.9733333333333334)

In [ ]:
y_pred = classifier_regressior.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
score = accuracy_score(y_pred, y_test)
score

0.96

In [ ]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.93      1.00      0.96        13
           1       1.00      0.92      0.96        12

    accuracy                           0.96        25
   macro avg       0.96      0.96      0.96        25
weighted avg       0.96      0.96      0.96        25